### ISSUE TITLE
CVPR 2024 LaTeX Template: Windows Compatibility Issues

### ISSUE THREAD

**Issue by zhazhiyuan** [cvpr-org/author-kit#15] opened 2023-09-15 20:09 UTC
While the template runs successfully on Overleaf, I have been experiencing consistent errors when trying to compile it locally on a Windows system. The error message is displayed as shown in the attached image. I consulted with other members of our lab who are also using Windows, and they reported encountering the same issue. However, when the template was tested on a Mac using TeXShop, it worked seamlessly. 

Based on my observations, it seems that the current Latex template might not be fully compatible with Windows systems. I would appreciate it if you could kindly investigate this issue and possibly provide a resolution or guidance on how to work around it. 
![Error](https://github.com/cvpr-org/author-kit/assets/23114731/e113ad28-4d7f-45cb-aa31-11d1232babcd)

**Comment by licongguan** [comment] 2023-09-19 11:35
Delete \RequirePackage{cite} % Automatically ordered citations in cvpr.sty

**Comment by cr333** [comment] 2023-10-12 16:59
This issue seems to be unrelated to the cite package.

@zhazhiyuan:
Do you observe this error on a fresh check-out of this repo?
Could you please post a complete copy of the log you get from LaTeX?
That should also contain your LaTeX version.

This information would be helpful for debugging this issue, as I cannot reproduce it on my Windows LaTeX setup (pdfTeX, Version 3.141592653-2.6-1.40.25 (MiKTeX 23.5)).

**Comment by zhazhiyuan** [comment] 2023-10-13 01:28
Dear Dr. Richardt, the complete log is as follows. Currently, I use the overleaf to deal with our work. @cr333 

Command Line:   texify.exe --pdf --tex-option=--interaction=errorstopmode --tex-option=--synctex=1 "C:\Users\zhazh\Downloads\author-kit-CVPR2024-v2\main.tex"
Startup Folder: C:\Users\zhazh\Downloads\author-kit-CVPR2024-v2

This is pdfTeX, Version 3.1415926-2.3-1.40.12 (MiKTeX 2.9)
entering extended mode
(C:/Users/zhazh/Downloads/author-kit-CVPR2024-v2/main.tex
LaTeX2e <2011/06/27>
Babel <v3.8m> and hyphenation patterns for loaded.
(C:\CTEX\MiKTeX\tex\latex\base\article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(C:\CTEX\MiKTeX\tex\latex\base\size10.clo))
(C:\Users\zhazh\Downloads\author-kit-CVPR2024-v2\cvpr.sty
(C:\CTEX\MiKTeX\tex\latex\psnfss\times.sty)
(C:\CTEX\MiKTeX\tex\latex\cite\cite.sty)
(C:\CTEX\MiKTeX\tex\latex\tools\xspace.sty)
(C:\CTEX\MiKTeX\tex\latex\graphics\graphicx.sty
(C:\CTEX\MiKTeX\tex\latex\graphics\keyval.sty)
(C:\CTEX\MiKTeX\tex\latex\graphics\graphics.sty
(C:\CTEX\MiKTeX\tex\latex\graphics\trig.sty)
(C:\CTEX\MiKTeX\tex\latex\00miktex\graphics.cfg)
(C:\CTEX\MiKTeX\tex\latex\pdftex-def\pdftex.def
(C:\CTEX\MiKTeX\tex\generic\oberdiek\infwarerr.sty)
(C:\CTEX\MiKTeX\tex\generic\oberdiek\ltxcmds.sty))))
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsmath.sty
For additional information on amsmath, use the `?' option.
(C:\CTEX\MiKTeX\tex\latex\ams\math\amstext.sty
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsgen.sty))
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsbsy.sty)
(C:\CTEX\MiKTeX\tex\latex\ams\math\amsopn.sty))
(C:\CTEX\MiKTeX\tex\latex\amsfonts\amssymb.sty
(C:\CTEX\MiKTeX\tex\latex\amsfonts\amsfonts.sty))
(C:\CTEX\MiKTeX\tex\latex\booktabs\booktabs.sty)
(C:\CTEX\MiKTeX\tex\latex\natbib\natbib.sty

Package natbib Warning: The `cite' package should not be used
(natbib)                with natbib. Use option `sort' instead.

) (C:\CTEX\MiKTeX\tex\latex\silence\silence.sty)
(C:\CTEX\MiKTeX\tex\latex\etoolbox\etoolbox.sty
(C:\CTEX\MiKTeX\tex\latex\misc\etex.sty))
(C:\CTEX\MiKTeX\tex\latex\caption\caption.sty
(C:\CTEX\MiKTeX\tex\latex\caption\caption3.sty))
(C:\CTEX\MiKTeX\tex\latex\caption\subcaption.sty)
(C:\CTEX\MiKTeX\tex\latex\ltxmisc\url.sty)
CVPR 8.5 x 11-Inch Proceedings Style `cvpr.sty'.
(C:\CTEX\MiKTeX\tex\latex\lineno\lineno.sty)
(C:\CTEX\MiKTeX\tex\latex\enumitem\enumitem.sty))
! Missing = inserted for \ifnum.
<to be read again> 
                   E
l.9 
    
?

**Comment by cr333** [comment] 2023-10-19 12:06
Thank you for sharing this more complete log.

It looks like including the `cvpr` package completes successfully (line 7 of `main.tex`), and the error appears sometime after that and before including `preamble.tex` (line 11 of `main.tex`), as that filename does not appear in your log.

My best guess is that something breaks because of an outdated LaTeX distribution. You are using "pdfTeX, Version 3.1415926-2.3-1.40.12", which was [released on 2011-06-20](https://www.tug.org/applications/pdftex/NEWS) as part of TeX Live 2011 more than 10 years ago.

I’m afraid we cannot support such old LaTeX distributions and I am therefore closing this issue.

I would strongly encourage you to install a more recent distribution.

**Closed** 2023-10-19 12:11 UTC
